app:
  image: matomo:fpm
  volumes:
    - ./config:/var/www/html/config:rw
    - ./logs:/var/www/html/logs
  env_file:
    - ./matomo.env
  restart: always
web:
  image: nginx:latest
  volumes:
    - ./docker-nginx.conf:/etc/nginx/nginx.conf:ro
  links:
    - app
  volumes_from:
    - app
  ports:
    - 127.0.0.1:8001:80
  restart: always


