# Dockerfile
FROM node

# create destination directory
RUN mkdir -p /usr/src/nuxt-output

# copy the app, note .dockerignore
COPY Frontend.Web.Nuxt/.output /usr/src/nuxt-output/

EXPOSE 3000

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

WORKDIR /usr/src/nuxt-output
CMD [ "node", "server/index.mjs"]