version: "3.9"
services:
  mem-nuxt:
    image: ghcr.io/memowikis/mem-nuxt:${BUILD_NUMBER:-error}
    # expose:
      # - "3000"
    ports:
      - "${NUXT_PORT:-3000}:3000"
      # Probably only needed in Development for Hot Module Reloading:
      # - "${NUXT_HMR_PORT:-24678}:24678"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - environment-specific-network
    environment:
      - NUXT_PUBLIC_SERVER_BASE=${NUXT_PUBLIC_SERVER_BASE:-error}
      - NUXT_PUBLIC_GSI_CLIENT_KEY=${NUXT_PUBLIC_GSI_CLIENT_KEY:-error}
      - NUXT_PUPLIC_SEQ_SERVER_PORT=${NUXT_PUBLIC_SEQ_SERVER_PORT}
      - NUXT_PUBLIC_SEQ_SERVER_URL=${NUXT_PUBLIC_SEQ_SERVER_URL}
      - NUXT_SEQ_RAW_URL=${NUXT_SEQ_RAW_URL}
      - NUXT_SEQ_SERVER_API_KEY=${NUXT_SEQ_SERVER_API_KEY}
      - NUXT_PUBLIC_SEQ_CLIENT_API_KEY=${NUXT_PUBLIC_SEQ_CLIENT_API_KEY}
      - NUXT_PUBLIC_STRIPE_PLUS_PRICE_ID=${NUXT_PUBLIC_STRIPE_PLUS_PRICE_ID}
      - NUXT_PUBLIC_STRIPE_KEY=${NUXT_PUBLIC_STRIPE_KEY}
      - NUXT_PUBLIC_FACEBOOK_APP_ID=${NUXT_PUBLIC_FACEBOOK_APP_ID}
  redis:
    deploy:
      restart_policy:
        condition: always
networks:
  environment-specific-network:
    name: mem-${MEM_ENVIRONMENT:-stage}
    # Was already set up with nginx: 
    external: true

# Start nginx in network with name mem-stage first (see seperate docker-compose), run command with -p mem-${MEM_ENVIRONMENT}
# Run in bash like this:
# $ export BUILD_NUMBER=5408
# $ docker-compose -p mem-stage up -d
# will recreate a running container