version: '3.9'

services:
  mem-nginx-reverse-stage:
    image: nginx:1.25.1
    build: .
    ports:
      - "3002:3002"
    environment:
      - SERVER_PORT=3002
      - HOST_VAR=https://stage.memucho.de
      - PORT_NUXT=3003
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./robots.txt:/etc/nginx/html/robots.txt
    command:  /bin/sh -c "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/nginx.conf &&
              /usr/sbin/nginx -g 'daemon off;'"
    networks:
      - environment-specific-network
    restart: always

networks:
  environment-specific-network:
    name: mem-test
    driver: bridge
