version: '3.9'

services:
  mem-nginx-reverse-stage:
    image: nginx:alpine
    build: .
    ports:
      - "5002:5002"
    environment:
      - SERVER_PORT=5002
      - HOST_VAR=https://stage.memucho.de
      - PORT_NUXT=3002
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./robots.stage.txt:/etc/nginx/html/robots.txt
    command:  /bin/sh -c "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/nginx.conf &&
              /usr/sbin/nginx -g 'daemon off;'"
    networks:
      - environment-specific-network

networks:
  environment-specific-network:
    name: mem-stage
    driver: bridge

# Start like this:
# docker-compose -f docker-compose.stage.yml -p mem-stage up -d
