version: '3.9'

services:
  mem-nginx-reverse-live:
    image: nginx:1.25.1
    build: .
    ports:
      - "5001:5001"
    environment:
      - SERVER_PORT=5001
      - HOST_VAR=http://live.memucho.de
      - PORT_NUXT=3001
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
      - ./robots.live.txt:/etc/nginx/html/robots.txt
    command:  /bin/sh -c "envsubst < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/nginx.conf &&
              /usr/sbin/nginx -g 'daemon off;'"
    networks:
      - environment-specific-network
    deploy:
      restart_policy:
        condition: always
networks:
  environment-specific-network:
    name: mem-live
    driver: bridge

# Start like this:
# docker-compose -f docker-compose.live.yml -p mem-live up -d