// window.tiptapBuild = {
//     tiptap: require("tiptap"),
//     tiptapUtils: require("tiptap-utils"),
//     tiptapCommands: require("tiptap-commands"),
//     tiptapExtensions: require("tiptap-extensions"),
// };

window.tiptapBuildV2 = {
    tiptapVue: require("@tiptap/vue-2"),
    tiptapStarterKit: require("@tiptap/starter-kit"),
    tiptapExtensionBlockquote: require("@tiptap/extension-blockquote"),
    tiptapExtensionBold: require("@tiptap/extension-bold"),
    tiptapExtensionBulletList: require("@tiptap/extension-bullet-list"),
    tiptapExtensionCode: require("@tiptap/extension-code"),
    tiptapExtensionCodeBlock: require("@tiptap/extension-code-block"),
    tiptapExtensionCodeBlockLowlight: require("@tiptap/extension-code-block-lowlight"),
    tiptapExtensionDocument: require("@tiptap/extension-document"),
    tiptapExtensionDropCursor: require("@tiptap/extension-dropcursor"),
    tiptapExtensionGapCursor: require("@tiptap/extension-gapcursor"),
    tiptapExtensionHardBreak: require("@tiptap/extension-hard-break"),
    tiptapExtensionHeading: require("@tiptap/extension-heading"),
    tiptapExtensionHistory: require("@tiptap/extension-history"),
    tiptapExtensionHorizontalRule: require("@tiptap/extension-horizontal-rule"),
    tiptapExtensionImage: require("@tiptap/extension-image"),    
    tiptapExtensionItalic: require("@tiptap/extension-italic"),
    tiptapExtensionLink: require("@tiptap/extension-link"),
    tiptapExtensionListItem: require("@tiptap/extension-list-item"),
    tiptapExtensionOrderedList: require("@tiptap/extension-ordered-list"),
    tiptapExtensionParagraph: require("@tiptap/extension-paragraph"),
    tiptapExtensionStrike: require("@tiptap/extension-strike"),
    tiptapExtensionText: require("@tiptap/extension-text")
};

window.hljsBuild = {
    apache: require("highlight.js/lib/languages/apache"),
    cLike: require("highlight.js/lib/languages/c-like"),
    xml: require("highlight.js/lib/languages/xml"),
    bash: require("highlight.js/lib/languages/bash"),
    c: require("highlight.js/lib/languages/c"),
    coffeescript: require("highlight.js/lib/languages/coffeescript"),
    csharp: require("highlight.js/lib/languages/csharp"),
    css: require("highlight.js/lib/languages/css"),
    markdown: require("highlight.js/lib/languages/markdown"),
    diff: require("highlight.js/lib/languages/diff"),
    ruby: require("highlight.js/lib/languages/ruby"),
    go: require("highlight.js/lib/languages/go"),
    http: require("highlight.js/lib/languages/http"),
    ini: require("highlight.js/lib/languages/ini"),
    java: require("highlight.js/lib/languages/java"),
    javascript: require("highlight.js/lib/languages/javascript"),
    json: require("highlight.js/lib/languages/json"),
    kotlin: require("highlight.js/lib/languages/kotlin"),
    less: require("highlight.js/lib/languages/less"),
    lua: require("highlight.js/lib/languages/lua"),
    makefile: require("highlight.js/lib/languages/makefile"),
    perl: require("highlight.js/lib/languages/perl"),
    nginx: require("highlight.js/lib/languages/nginx"),
    objectivec: require("highlight.js/lib/languages/objectivec"),
    php: require("highlight.js/lib/languages/php"),
    phpTemplate: require("highlight.js/lib/languages/php-template"),
    plaintext: require("highlight.js/lib/languages/plaintext"),
    properties: require("highlight.js/lib/languages/properties"),
    python: require("highlight.js/lib/languages/python"),
    pythonREPL: require("highlight.js/lib/languages/python-repl"),
    rust: require("highlight.js/lib/languages/rust"),
    scss: require("highlight.js/lib/languages/scss"),
    shell: require("highlight.js/lib/languages/shell"),
    sql: require("highlight.js/lib/languages/sql"),
    swift: require("highlight.js/lib/languages/swift"),
    yaml: require("highlight.js/lib/languages/yaml"),
    typescript: require("highlight.js/lib/languages/typescript"),
    core: require("highlight.js")
};