# First stage: build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# Copy csproj and restore as distinct layers
COPY TrueOrFalse/*.csproj TrueOrFalse/
COPY TrueOrFalse.Frontend.Web/*.csproj TrueOrFalse.Frontend.Web/
RUN dotnet restore TrueOrFalse/TrueOrFalse.csproj
RUN dotnet restore TrueOrFalse.Frontend.Web/TrueOrFalse.Frontend.Web.csproj

# Copy and build app and libraries
COPY TrueOrFalse/ TrueOrFalse/
COPY TrueOrFalse.Frontend.Web/ TrueOrFalse.Frontend.Web
WORKDIR /source/TrueOrFalse.Frontend.Web
RUN dotnet publish TrueOrFalse.Frontend.Web.csproj --no-restore -c Release -o /app

# Second stage: build the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "TrueOrFalse.View.Web.dll"]