# First stage: build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

# Check .NET Core SDK version
RUN dotnet --info

# Copy csproj and restore as distinct layers
COPY Backend.Core/*.csproj Backend.Core/
COPY Backend.Api/*.csproj Backend.Api/
RUN dotnet restore Backend.Core/Backend.Core.csproj
RUN dotnet restore Backend.Api/Backend.Api.csproj

# Copy and build app and libraries
COPY Backend.Core/ Backend.Core/
COPY Backend.Api/ Backend.Api
WORKDIR /source/Backend.Api
RUN dotnet publish Backend.Api.csproj --no-restore -c Release -o /app -p:LangVersion=13.0

# Second stage: build the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "Backend.Api.dll"]