version: '3.9'
services:
  meilisearch:
    image: getmeili/meilisearch:v0.30
    command: ["meilisearch", "--master-key=${MEILI_MASTER_KEY}"]
    restart: always
    ports:
      - "${MEILI_PORT}:7700"
    volumes:
      - C:/Meilisearch/${ENVIRONMENT}:/meili_data

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - C:/redis-data/${ENVIRONMENT}:/data
      
  hocuspocus:
    build:
      context: ../../hocuspocus  # Relative path to your Express app and Dockerfile
    ports:
      - "3010:3010"  # Port mapping for your Express app
    environment:
      NODE_ENV: development