version: '3.9'
services:
  meilisearch:
    image: getmeili/meilisearch:v0.30
    command: ["meilisearch", "--master-key=${MEILI_MASTER_KEY}"]
    restart: always
    ports:
      - "${MEILI_PORT}:7700"
    volumes:
      - C:/Meilisearch/${MEM_ENVIRONMENT}:/meili_data
      
  redis:
    image: redis:7.2.4
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
  
