version: '3.9'
services:
  meilisearch:
    image: getmeili/meilisearch:v0.30
    command: ["meilisearch", "--master-key=${MEILI_MASTER_KEY}"]
    restart: always
    ports:
      - "${MEILI_PORT}:7700"
    volumes:
      - C:/Meilisearch/${MEM_ENVIRONMENT}:/meili_data

    meilisearchTest:
      image: getmeili/meilisearch:v0.30
      command: ["meilisearch", "--master-key=nuxt1234"]
      restart: always
      ports:
        - "7001:7700"
      volumes:
        - C:/Meilisearch/${MEM_ENVIRONMENT}:/meili_data_test

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
