# Use the official Node.js image as the base image
FROM node

ENV ENVIRONMENT=dev
ENV REDIS_HOST=host.docker.internal
ENV REDIS_PORT=6379
ENV HOCUSPOCUS_SECRET_KEY=abrakadabrakey
ENV BACKEND_BASE_URL=http://host.docker.internal:5069

# Set the working directory in the container
RUN mkdir -p /usr/src/hocuspocus-app
WORKDIR /usr/src/hocuspocus-app

#copy the app
COPY . .

# Install the app dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 3010

# Define the command to start the app
CMD ["npm", "start"]